#!/bin/sh

. ./.init-public

curl -X GET \
  -H "web-api-key: $apikey" \
  $apiroot/v2/transparentAccounts/${1:-000000-0006196112} \
| js-beautify -s 2 -w 111 \
> "$0${1:+-$1}${2:+-$2}${3:+-$3}${4:+-$4}.json"
