#!/bin/sh

. ./.init-auth

curl -X GET \
  -H "web-api-key: $apikey" \
  -H "authorization: Bearer $token" \
  $apiroot/v3/netbanking/my/orders/payments/domestic \
  -H 'content-type: application/json' \
  -d '{
  "transferDate": "2017-11-24",
  "orderCategory": "DOMESTIC",
  "orderType": "PAYMENT_OUT",
  "senderName": "Apinaut super aplikace",

  "sender": {
    "countryCode": "CZ",
    "iban": "CZ2708000000002757413113",
    "bic": "GIBACZPX"
  },

  "receiverName": "Muj tajnej ucet pro dovolenou na Bahamy",

  "receiver": {
    "number": "2427559339",
    "bankCode": "0800",
    "countryCode": "CZ",
    "cz-iban": "CZ2908000000002427559339",
    "cz-bic": "GIBACZPX"
  },

  "amount": {
    "value": 101,
    "precision": 2,
    "currency": "CZK"
  },

  "symbols": {
    "variableSymbol": "789",
    "constantSymbol": "456",
    "specificSymbol": "123"

  },

  "senderReference": "Apinaut to Bahamy",

  "additionalInfo": {
    "text4x35": [
      "Dej kus apky do svy banky"
    ]
  }
}' \
| js-beautify -s 2 -w 111 \
> "../data/$0.json"
